changelog:
  exclude:
    labels:
      - ignore-for-release
      - release
    authors:
      - github-actions[bot]
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: New Examples
      labels:
        - examples
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - "*"
