/**
 * MCP Schema Generation Script
 *
 * Generates Zod schemas from the vendored MCP spec types (src/vendor/mcp-types.ts)
 * using ts-to-zod. The output (src/generated/mcp-schemas.ts) provides schemas like
 * ContentBlockSchema, CallToolResultSchema, ToolSchema, etc. that are consumed by
 * the main schema generator (generate-schemas.ts) and the rest of the SDK.
 *
 * Post-processing:
 * - Rewrites `import { z } from "zod"` to `import { z } from "zod/v4"`
 * - Replaces `z.record().and(z.object({...}))` with `z.object({...}).passthrough()`
 * - Adds a header comment noting the source
 *
 * @see scripts/generate-schemas.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generate } from "ts-to-zod";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, "..");

const MCP_TYPES_FILE = join(PROJECT_ROOT, "src", "vendor", "mcp-types.ts");
const GENERATED_DIR = join(PROJECT_ROOT, "src", "generated");
const OUTPUT_FILE = join(GENERATED_DIR, "mcp-schemas.ts");

function main() {
  console.log("Generating MCP Zod schemas from vendor/mcp-types.ts...\n");

  const sourceText = readFileSync(MCP_TYPES_FILE, "utf-8");

  const result = generate({
    sourceText,
    keepComments: true,
    skipParseJSDoc: false,
    getSchemaName: (typeName: string) => `${typeName}Schema`,
  });

  if (result.errors.length > 0) {
    console.error("Generation errors:");
    for (const error of result.errors) {
      console.error(`  - ${error}`);
    }
    process.exit(1);
  }

  if (result.hasCircularDependencies) {
    console.warn("Warning: Circular dependencies detected in MCP types");
  }

  let content = result.getZodSchemasFile("../vendor/mcp-types.js");
  content = postProcess(content);

  writeFileSync(OUTPUT_FILE, content, "utf-8");
  console.log(`Written: ${OUTPUT_FILE}`);
  console.log("\nMCP schema generation complete!");
}

/**
 * Post-process generated schemas for project compatibility.
 */
function postProcess(content: string): string {
  // 1. Rewrite zod import to zod/v4
  content = content.replace(
    'import { z } from "zod";',
    'import { z } from "zod/v4";',
  );

  // 2. Replace z.record().and(z.object({...})) with z.object({...}).passthrough()
  content = replaceRecordAndWithPassthrough(content);

  // 3. Add header comment
  content = content.replace(
    "// Generated by ts-to-zod",
    `// Generated by ts-to-zod from src/vendor/mcp-types.ts
// Source: MCP spec schema/2025-11-25/schema.ts
// Run: npm run generate:mcp-schemas`,
  );

  return content;
}

/**
 * Replace z.record(z.string(), z.unknown()).and(z.object({...})) with z.object({...}).passthrough()
 * Uses brace-counting to handle nested objects correctly.
 * passthrough() works in both Zod v3 and v4, allowing extra properties.
 */
function replaceRecordAndWithPassthrough(content: string): string {
  const pattern = "z.record(z.string(), z.unknown()).and(z.object({";
  let result = content;
  let startIndex = 0;

  while (true) {
    const matchStart = result.indexOf(pattern, startIndex);
    if (matchStart === -1) break;

    // Find the matching closing brace for z.object({
    const objectStart = matchStart + pattern.length;
    let braceCount = 1;
    let i = objectStart;

    while (i < result.length && braceCount > 0) {
      if (result[i] === "{") braceCount++;
      else if (result[i] === "}") braceCount--;
      i++;
    }

    // i now points after the closing } of z.object({...})
    // Check if followed by ))
    if (result.slice(i, i + 2) === "))") {
      const objectContent = result.slice(objectStart, i - 1);
      const replacement = `z.object({${objectContent}}).passthrough()`;
      result = result.slice(0, matchStart) + replacement + result.slice(i + 2);
      startIndex = matchStart + replacement.length;
    } else {
      startIndex = i;
    }
  }

  return result;
}

main();
