/**
 * Post-processes the generated schemas from ts-to-zod for Zod v4 compatibility
 * and to use proper MCP SDK schema imports.
 *
 * ts-to-zod generates code that has compatibility issues:
 * 1. Uses "zod" import instead of "zod/v4"
 * 2. Uses z.any() for external type references
 * 3. Uses z.record().and(z.object()) for index signatures which doesn't work well
 *
 * This script fixes these issues.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, "..");

const SCHEMA_FILE = join(PROJECT_ROOT, "src", "schemas.generated.ts");

function main() {
  console.log(
    "Post-processing generated schemas for Zod v4 and MCP SDK compatibility...",
  );

  let content = readFileSync(SCHEMA_FILE, "utf-8");

  // 1. Update import to use zod/v4 and add MCP SDK imports
  content = content.replace(
    'import { z } from "zod";',
    `import { z } from "zod/v4";
import {
    CallToolResultSchema,
    ContentBlockSchema,
    ImplementationSchema,
    RequestIdSchema,
    ToolSchema
} from "@modelcontextprotocol/sdk/types.js";`,
  );

  // 2. Add post-processing comment
  content = content.replace(
    "// Generated by ts-to-zod",
    "// Generated by ts-to-zod\n// Post-processed for Zod v4 compatibility (run: npm run generate:schemas)",
  );

  // 3. Replace z.any() placeholders for MCP SDK types with proper imports
  content = content.replace(
    /const contentBlockSchema = z\.any\(\);/g,
    "const contentBlockSchema = ContentBlockSchema;",
  );
  content = content.replace(
    /const callToolResultSchema = z\.any\(\);/g,
    "const callToolResultSchema = CallToolResultSchema;",
  );
  content = content.replace(
    /const requestIdSchema = z\.any\(\);/g,
    "const requestIdSchema = RequestIdSchema;",
  );
  content = content.replace(
    /const toolSchema = z\.any\(\);/g,
    "const toolSchema = ToolSchema;",
  );
  content = content.replace(
    /const implementationSchema = z\.any\(\);/g,
    "const implementationSchema = ImplementationSchema;",
  );

  // 4. Replace z.record().and(z.object()) patterns with z.looseObject()
  // These patterns don't work well with Zod v4 and schema composition
  content = content.replace(
    /export const (mcpUi\w+Schema) = z\.record\(z\.string\(\), z\.unknown\(\)\)\.and\(z\.object\(\{([^}]*)\}\)\);/gs,
    (match, schemaName, objectContent) => {
      // Format the object content properly
      const formattedContent = objectContent.trim();
      return `export const ${schemaName} = z.looseObject({${formattedContent}});`;
    },
  );

  writeFileSync(SCHEMA_FILE, content, "utf-8");
  console.log("Post-processing complete!");
}

main();
