// Generated by ts-to-zod
// Post-processed for Zod v4 compatibility (run: npm run generate:schemas)
import { z } from "zod/v4";
import {
    CallToolResultSchema,
    ContentBlockSchema,
    ImplementationSchema,
    RequestIdSchema,
    ToolSchema
} from "@modelcontextprotocol/sdk/types.js";

export const mcpUiOpenLinkRequestSchema = z.object({
    method: z.literal("ui/open-link"),
    params: z.object({
        url: z.string()
    })
});

export const mcpUiOpenLinkResultSchema = z.looseObject({isError: z.boolean().optional()});

export const mcpUiMessageResultSchema = z.looseObject({isError: z.boolean().optional()});

export const mcpUiSandboxProxyReadyNotificationSchema = z.object({
    method: z.literal("ui/notifications/sandbox-proxy-ready"),
    params: z.object({})
});

export const mcpUiSandboxResourceReadyNotificationSchema = z.object({
    method: z.literal("ui/notifications/sandbox-resource-ready"),
    params: z.object({
        html: z.string(),
        sandbox: z.string().optional()
    })
});

export const mcpUiSizeChangeNotificationSchema = z.object({
    method: z.literal("ui/notifications/size-change"),
    params: z.object({
        width: z.number().optional(),
        height: z.number().optional()
    })
});

export const mcpUiToolInputNotificationSchema = z.object({
    method: z.literal("ui/notifications/tool-input"),
    params: z.object({
        arguments: z.record(z.string(), z.unknown()).optional()
    })
});

export const mcpUiToolInputPartialNotificationSchema = z.object({
    method: z.literal("ui/notifications/tool-input-partial"),
    params: z.object({
        arguments: z.record(z.string(), z.unknown()).optional()
    })
});

export const mcpUiResourceTeardownRequestSchema = z.object({
    method: z.literal("ui/resource-teardown"),
    params: z.object({})
});

export const mcpUiResourceTeardownResultSchema = z.object({});

export const mcpUiHostCapabilitiesSchema = z.object({
    experimental: z.object({}).optional(),
    openLinks: z.object({}).optional(),
    serverTools: z.object({
        listChanged: z.boolean().optional()
    }).optional(),
    serverResources: z.object({
        listChanged: z.boolean().optional()
    }).optional(),
    logging: z.object({}).optional()
});

export const mcpUiAppCapabilitiesSchema = z.object({
    experimental: z.object({}).optional(),
    tools: z.object({
        listChanged: z.boolean().optional()
    }).optional()
});

export const mcpUiInitializedNotificationSchema = z.object({
    method: z.literal("ui/notifications/initialized"),
    params: z.object({}).optional()
});

const contentBlockSchema = ContentBlockSchema;

const callToolResultSchema = CallToolResultSchema;

const requestIdSchema = RequestIdSchema;

const toolSchema = ToolSchema;

const implementationSchema = ImplementationSchema;

export const mcpUiMessageRequestSchema = z.object({
    method: z.literal("ui/message"),
    params: z.object({
        role: z.literal("user"),
        content: z.array(contentBlockSchema)
    })
});

export const mcpUiToolResultNotificationSchema = z.object({
    method: z.literal("ui/notifications/tool-result"),
    params: callToolResultSchema
});

export const mcpUiHostContextSchema = z.object({
    toolInfo: z.object({
        id: requestIdSchema,
        tool: toolSchema
    }).optional(),
    theme: z.union([z.literal("light"), z.literal("dark"), z.literal("system")]).optional(),
    displayMode: z.union([z.literal("inline"), z.literal("fullscreen"), z.literal("pip"), z.literal("carousel")]).optional(),
    availableDisplayModes: z.array(z.string()).optional(),
    viewport: z.object({
        width: z.number(),
        height: z.number(),
        maxHeight: z.number().optional(),
        maxWidth: z.number().optional()
    }).optional(),
    locale: z.string().optional(),
    timeZone: z.string().optional(),
    userAgent: z.string().optional(),
    platform: z.union([z.literal("web"), z.literal("desktop"), z.literal("mobile")]).optional(),
    deviceCapabilities: z.object({
        touch: z.boolean().optional(),
        hover: z.boolean().optional()
    }).optional(),
    safeAreaInsets: z.object({
        top: z.number(),
        right: z.number(),
        bottom: z.number(),
        left: z.number()
    }).optional()
});

export const mcpUiHostContextChangedNotificationSchema = z.object({
    method: z.literal("ui/notifications/host-context-changed"),
    params: mcpUiHostContextSchema
});

export const mcpUiInitializeRequestSchema = z.object({
    method: z.literal("ui/initialize"),
    params: z.object({
        appInfo: implementationSchema,
        appCapabilities: mcpUiAppCapabilitiesSchema,
        protocolVersion: z.string()
    })
});

export const mcpUiInitializeResultSchema = z.looseObject({protocolVersion: z.string(),
    hostInfo: implementationSchema,
    hostCapabilities: mcpUiHostCapabilitiesSchema,
    hostContext: mcpUiHostContextSchema});
